# Generated by Django 4.1 on 2022-08-27 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 27, 19, 46, 47, 29654, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="useractivationcode",
            name="expire_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2022, 8, 28, 19, 46, 47, 29654, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
