# Generated by Django 4.1 on 2022-09-05 11:48

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="useractivationcode",
            name="expire_date",
            field=models.DateTimeField(default=accounts.models.one_day_hence),
        ),
        migrations.AlterField(
            model_name="userrecoverycode",
            name="expire_date",
            field=models.DateTimeField(default=accounts.models.one_day_hence),
        ),
    ]
