# Generated by Django 4.1 on 2022-09-04 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DentalDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_favorite", models.BooleanField(default=False)),
                (
                    "danger_percentage",
                    models.DecimalField(decimal_places=2, max_digits=3),
                ),
                ("name", models.CharField(max_length=25)),
                ("description", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "diagnosis_dental_diagnosis",
            },
        ),
        migrations.CreateModel(
            name="DentalDiagnosisDentureImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=255)),
                (
                    "dental_diagnosis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dental_diagnosis_denture_images",
                        to="diagnosis.dentaldiagnosis",
                    ),
                ),
            ],
            options={
                "db_table": "diagnosis_dental_diagnosis_denture_image",
            },
        ),
    ]
